version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: 'api-backend'
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: 'api-db'
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api

  redis:
    image: 'bitnami/redis:latest'
    container_name: 'api-redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: 'api-pgadmin'
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
